apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://backstage.github.io/charts
    chart: backstage
    targetRevision: 2.6.3
    helm:
      releaseName: backstage
      values: |
        postgresql:  ##### disable the postgresql chart that comes with backstage, it installs the postgresql chart from the chart repo too, instead of this we are using the cloud sql
          enabled: false

        backstage:
          image:
            registry: ghcr.io
            repository: backstage/backstage
            tag: 1.46.0
            pullPolicy: IfNotPresent

          # These extra vars for the backstage container 
          # cause backstae needs github access to read reposotories, load catalog & template, create pull requests, etc...
          extraEnvVars:
            # ✅ 1. Inject the GitHub Token
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: backstage-github-token
                  key: GITHUB_TOKEN

            ## as the Backstage needs to store its internal data like tempalte run logs, user sessions we can't store in github, so we are suing cloud sql as our db passing these variables...
            # Database Vars
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: backstage-pg-secret
                  key: publicIP
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: "backstage-user"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backstage-db-password
                  key: password

          appConfig:  
            app:
              baseUrl: http://localhost:7007   # this PART wehre URL where Backstage runs
              title: Omnitrix Portal
            
            # ✅ 2. Add Integrations Block
            integrations:
              github:
                - host: github.com
                  token: ${GITHUB_TOKEN}  # this connects the backsgte to gihub to use public github with the github token env variable, as we are using the PAT we don't require the username 

            auth:
              providers:
                guest: {}   ## this enables guest login, anyone who opens Backstage can enter with no pswd or username 
            backend:
              auth:
                dangerouslyDisableDefaultAuthPolicy: true
              baseUrl: http://localhost:7007
              reading:
                allow:
                  - host: raw.githubusercontent.com
                  - host: github.com
              database:
                client: pg
                connection:
                  host: ${POSTGRES_HOST}
                  port: ${POSTGRES_PORT}
                  user: ${POSTGRES_USER}
                  password: ${POSTGRES_PASSWORD}
                  ssl:
                    rejectUnauthorized: false
            catalog:
              rules:
                - allow: [Component, System, API, Resource, Location, Template]

              ## we are passing two locations to backstage, frist is loads your main service catalog like (compontes, systems, API)
              ## second location is of the template that we created, this template is used to create a new GCS bucket... (like GCS bucket creation, PR creation)
              locations:
                - type: url
                  target: https://raw.githubusercontent.com/UltimateOmnitrix/platform-monorepo/main/catalog-info.yaml
                - type: url
                  target: https://github.com/UltimateOmnitrix/platform-monorepo/blob/main/backstage/templates/gcs-bucket/template.yml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
