apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://backstage.github.io/charts
    chart: backstage
    targetRevision: 2.6.3
    helm:
      releaseName: backstage
      values: |
        postgresql:
          enabled: false

        backstage:
          image:
            registry: ghcr.io
            repository: backstage/backstage
            tag: 1.46.0
            pullPolicy: IfNotPresent
          
          extraEnvVars:
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: backstage-pg-secret
                  key: endpoint # ✅ FIXED: Changed publicIP to endpoint
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: "backstage-user"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backstage-db-password
                  key: password

          appConfig:
            app:
              baseUrl: http://localhost:7007
              title: Omnitrix Portal
            auth:
              providers:
                guest: {}
            backend:
              baseUrl: http://localhost:7007
              reading:
                allow:
                  - host: raw.githubusercontent.com
                  - host: github.com
              database:
                client: pg
                connection:
                  host: ${POSTGRES_HOST}
                  port: ${POSTGRES_PORT}
                  user: ${POSTGRES_USER}
                  password: ${POSTGRES_PASSWORD}
                  ssl:
                    rejectUnauthorized: false
            catalog:
              locations:
                - type: url
                  target: https://raw.githubusercontent.com/UltimateOmnitrix/platform-monorepo/main/catalog-info.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
