apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://backstage.github.io/charts
    chart: backstage
    targetRevision: 2.6.3
    helm:
      releaseName: backstage
      values: |
        postgresql:
          enabled: false

        backstage:
          image:
            registry: ghcr.io
            repository: backstage/backstage
            tag: 1.46.0
            pullPolicy: IfNotPresent

          extraEnvVars:
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: backstage-pg-secret
                  key: publicIP
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: "backstage-user"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backstage-db-password
                  key: password

          appConfig:
            app:
              baseUrl: http://localhost:7007
              title: Omnitrix Portal
            integrations:
              github:
                - host: github.com
            auth:
              providers:
                guest: {}
            backend:
              auth:
                dangerouslyDisableDefaultAuthPolicy: true
              baseUrl: http://localhost:7007
              reading:
                allow:
                  - host: raw.githubusercontent.com
                  - host: github.com
              database:
                client: pg
                connection:
                  host: ${POSTGRES_HOST}
                  port: ${POSTGRES_PORT}
                  user: ${POSTGRES_USER}
                  password: ${POSTGRES_PASSWORD}
                  ssl:
                    rejectUnauthorized: false
            
            # ✅ UPDATED CATALOG SECTION
            catalog:
              # 1. Allow Templates to be registered
              rules:
                - allow: [Component, System, API, Resource, Location, Template]
              
              # 2. Auto-register your files
              locations:
                # The main catalog passport
                - type: url
                  target: https://raw.githubusercontent.com/UltimateOmnitrix/platform-monorepo/main/catalog-info.yaml
                
                # The GCS Bucket Template (Note: using .yml extension)
                - type: url
                  target: https://raw.githubusercontent.com/UltimateOmnitrix/platform-monorepo/main/backstage/templates/gcs-bucket/template.yml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
