## this gets executed by argocd , then the Backstage app (backstage.yml) is installed in the cluster...

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: developer-portal
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/UltimateOmnitrix/platform-monorepo.git
    targetRevision: main
    path: registryGitOps/manifests/developer-portal
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
