apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: 1.2.0 # Stable version
    helm:
      releaseName: external-secrets

      ## We are passing these cause the helm doesn't install CRDs by default
      ## Usually for the helm charts, should install CRD's but in here there is not defualt so we are passing this parameter to install CRDs
      ## CRD = Custom Resource Definition
      ## A CRD is a file that tells Kubernetes:
      ## “I am adding a new kind of object to the Kubernetes API.”
      parameters:
        - name: installCRDs
          value: "true"

          ### NEEED TO WORK ON THIS WHY DID WE DO THIS is this neceesary?
        - name: serviceAccount.annotations.iam\.gke\.io/gcp-service-account
          value: "external-secrets-sa@platformproject-481722.iam.gserviceaccount.com"
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      ## getting error with metadata.annotations error as the below so need to use ServerSideApply
      #CustomResourceDefinition.apiextensions.k8s.io "secretstores.external-secrets.io" is invalid: metadata.annotations: Too long: may not be more than 262144 bytes
      - ServerSideApply=true
