apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: 1.2.0 # Stable version
    helm:
      releaseName: external-secrets

      ## We are passing these cause the helm doesn't install CRDs by default
      ## Usually for the helm charts, should install CRD's but in here there is not defualt so we are passing this parameter to install CRDs
      ## CRD = Custom Resource Definition
      ## A CRD is a file that tells Kubernetes:
      ## “I am adding a new kind of object to the Kubernetes API.”
      parameters:
        - name: installCRDs
          value: "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
