apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-gcs-bucket
  title: Create Google Cloud Storage Bucket
  description: Provisions a new GCS Bucket using Crossplane.
  tags:
    - gcp
    - storage
    - crossplane
spec:
  owner: platform-team
  type: service

  parameters:
    - title: Bucket Configuration
      required:
        - name
        - location
      properties:
        name:
          title: Bucket Name
          type: string
          description: Unique name for the bucket (e.g., my-app-logs)
          ui:autofocus: true
        location:
          title: Location
          type: string
          default: US
          enum:
            - US
            - EU
            - ASIA
          description: The region for the bucket.

  steps:
    - id: fetch-base
      name: Fetch Skeleton
      action: fetch:template
      input:
        url: ./skeleton
        values:
          name: ${{ parameters.name }}
          location: ${{ parameters.location }}

    - id: publish
      name: Create Pull Request
      action: publish:github:pull-request
      input:
        repoUrl: github.com?repo=platform-monorepo&owner=UltimateOmnitrix
        branchName: bucket-${{ parameters.name }}
        title: "Add GCS Bucket: ${{ parameters.name }}"
        description: "Creates a new GCS bucket via Crossplane"

  output:
    links:
      - title: View Pull Request
        url: ${{ steps.publish.output.remoteUrl }}
